# Generated by Django 4.1.4 on 2022-12-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grocery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("empty", "Empty"),
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("full", "Full"),
                        ],
                        default="empty",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
