# Generated by Django 4.1.4 on 2022-12-31 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_home_members"),
        ("depot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grocery",
            name="home",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="home.home"
            ),
            preserve_default=False,
        ),
    ]
