# Generated by Django 4.1.4 on 2022-12-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_django_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="member",
            name="staff",
            field=models.BooleanField(default=False),
        ),
    ]
