# Generated by Django 4.1.4 on 2022-12-25 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_super_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="home",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="home.home",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="home",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="home_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
